### ISSUE TITLE
RfSP Stopped working after 24.2 -> 24.3 update (Painter 7.4.1)

### ISSUE THREAD

**Issue by tdanijel** [pleprince/RfSP#40]
Hi Philippe, 

I know this is early as they just released 24.3 but maybe doesn't hurt to give you info from this side :)

- I have the latest renderman_for_sp.py file (Latest commit ff6ad88 on Nov 25, 2021)
- Just updated RenderMan to 24.3
- Windows 10 Pro has all the latest updates installed.
- Painter 7.4.1 build 1418 (latest version)
- The plugin was working fine with RMan 24.2
- I uninstalled RM 24.2 before updating (maybe not the smartest move)

ERROR LOG BEFORE CHANGING "Log(loglevel=spl.ERROR)" to line 103:

> [Resources List Model] Icons memory budget set to 100MB.
> [RenderMan 24.2.0] RMANTREE = 'C:/Program Files/Pixar/RenderManProServer-24.3'
> [RenderMan 24.2.0] Failed to import: cannot import name 'replace_img_with_tex' from 'rman_utils.rman_assets.common.external_files' (C:/Program Files/Pixar/RenderManProServer-24.3\bin\rman_utils\rman_assets\common\external_files.py)
> [Python] Traceback (most recent call last):
> 
> [Python]   File "C:/Users/danij/Documents/Adobe/Adobe Substance 3D Painter/python\plugins\renderman_for_sp.py", line 215, in build_panel
>     from rman_utils.rman_assets.common.external_files import (Storage, ExternalFileManager, replace_img_with_tex)
> 
> [Python] ImportError: cannot import name 'replace_img_with_tex' from 'rman_utils.rman_assets.common.external_files' (C:/Program Files/Pixar/RenderManProServer-24.3\bin\rman_utils\rman_assets\common\external_files.py)
> 
> [RenderMan 24.2.0] RenderMan started
> [Plugin - resources-updater] No project open, resources updater discarded

ERROR LOG AFTER ADDING "Log(loglevel=spl.DBG_INFO)" to line 103:

> [Resources List Model] Icons memory budget set to 100MB.
> [RenderMan 24.2.0] Log Level: LogSeverity.DBG_INFO (3)
> [RenderMan 24.2.0] SP python: 3.7.6
> [RenderMan 24.2.0] Log Level: LogSeverity.DBG_INFO (3)
> [RenderMan 24.2.0] SP python: 3.7.6
> [RenderMan 24.2.0] root = 'C:/Users/danij/Documents/Adobe/Adobe Substance 3D Painter/python\\plugins'
> [RenderMan 24.2.0] Loaded: C:\Users\danij\renderman_for_substance_painter.prefs
> [RenderMan 24.2.0] Prefs created
> [RenderMan 24.2.0] build_panel
> [RenderMan 24.2.0] RMANTREE = 'C:/Program Files/Pixar/RenderManProServer-24.3'
> [RenderMan 24.2.0] Failed to import: cannot import name 'replace_img_with_tex' from 'rman_utils.rman_assets.common.external_files' (C:/Program Files/Pixar/RenderManProServer-24.3\bin\rman_utils\rman_assets\common\external_files.py)
> [Python] Traceback (most recent call last):
> 
> [Python]   File "C:/Users/danij/Documents/Adobe/Adobe Substance 3D Painter/python\plugins\renderman_for_sp.py", line 215, in build_panel
>     from rman_utils.rman_assets.common.external_files import (Storage, ExternalFileManager, replace_img_with_tex)
> 
> [Python] ImportError: cannot import name 'replace_img_with_tex' from 'rman_utils.rman_assets.common.external_files' (C:/Program Files/Pixar/RenderManProServer-24.3\bin\rman_utils\rman_assets\common\external_files.py)
> 
> [RenderMan 24.2.0]   |_ done
> [RenderMan 24.2.0] RenderMan started
> [Plugin - resources-updater] No project open, resources updater discarded

Finally, thank you again for your work! I hope this was not too long of a post.

**Comment by pleprince** [comment]
Hi @tdanijel
I just published a new 24.3 branch to support the latest RenderMan.
I will look into supporting SP's new color management soon.
Cheers

**Comment by tdanijel** [comment]
Thank you kindly!
