### ISSUE TITLE
RfSP not working with 24.2

### ISSUE THREAD

**Issue by tristanGIANDO** [pleprince/RfSP#39]
Hello Philippe,
First of all, thanks a lot for your work, it's proven to have been really helpful in our workflow on making a short film.
Since we've updated to Renderman 24.2, the RfSP plugin interface suddenly changed. A section was added, named "Store Dependencies" with a tab offering either Asset, Library or External. It wasn't there beforehand, and we have tried using it nonetheless. 
Upon trying, we've noticed the same errors occurring: 
[Python]   File "C:/Users/t.giandoriggio/Documents/Adobe/Adobe Substance 3D Painter/python\plugins\renderman_for_sp.py", line 457, in exportMaterial
[Python] func()
[Python]   File "C:/Users/t.giandoriggio/Documents/Adobe/Adobe Substance 3D Painter/python\plugins\renderman_for_sp.py", line 897, in add_texture_node
[Python] func()
[Python]   File "C:/Users/t.giandoriggio/Documents/Adobe/Adobe Substance 3D Painter/python\plugins\renderman_for_sp.py", line 897, in add_texture_node
[Python] asset.addDependency(pdict['value'])
[Python] AttributeError
[Python] 'RmanAsset object has no attribute 'addDependency'. 

We've tried messing with the py file, adding an 'addDependency' attribute, but then it needs to be defined, and that's where we're stumped. 

Hope this is enough for you to work with, thank you again for your work!
All the best,
Tristan

**Comment by pleprince** [comment]
Hi @tristanGIANDO 
This has already been fixed. You must get the latest from the 24.1 branch and re-install.
Happy to hear it is helpful !

**Comment by tristanGIANDO** [comment]
Thanks very much, you're very efficient!
We'll be sure to credit you at the end of our student short film from ESMA, called Instinct, coming out next year ;)

**Comment by pleprince** [comment]
Looking forward to watching it... ESMA shorts are very often really good !
